# Generated by Django 6.0.6 on 2026-06-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeArquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('caminhoArquivo', models.CharField(max_length=255)),
                ('dataHoraUpload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Anexo',
            },
        ),
        migrations.CreateModel(
            name='ComentarioSubtarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ComentarioSubtarefa',
            },
        ),
        migrations.CreateModel(
            name='ComentarioTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ComentarioTarefa',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dataInicio', models.DateTimeField(blank=True, null=True)),
                ('dataFim', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Projeto',
            },
        ),
        migrations.CreateModel(
            name='Subtarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('dataInicio', models.DateTimeField(blank=True, null=True)),
                ('dataFim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
            ],
            options={
                'db_table': 'Subtarefa',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('dataInicio', models.DateTimeField(blank=True, null=True)),
                ('dataFim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
            ],
            options={
                'db_table': 'Tarefa',
            },
        ),
    ]
