# Generated by Django 6.0.6 on 2026-06-19 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentariosubtarefa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_subtarefas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentariotarefa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tarefas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(related_name='projetos_participando', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtarefa',
            name='participantes',
            field=models.ManyToManyField(related_name='subtarefas_participando', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentariosubtarefa',
            name='subtarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='boards.subtarefa'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='participantes',
            field=models.ManyToManyField(related_name='tarefas_participando', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='boards.projeto'),
        ),
        migrations.AddField(
            model_name='subtarefa',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='boards.tarefa'),
        ),
        migrations.AddField(
            model_name='comentariotarefa',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='boards.tarefa'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='boards.tarefa'),
        ),
    ]
