# Generated by Django 6.0.6 on 2026-07-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_projeto_criado_em_projeto_descricao_projeto_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='caminhoArquivo',
            field=models.FileField(upload_to='anexos/'),
        ),
    ]
