# Generated by Django 6.0.6 on 2026-07-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_anexo_caminhoarquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anexo',
            old_name='caminhoArquivo',
            new_name='caminho_arquivo',
        ),
        migrations.RenameField(
            model_name='anexo',
            old_name='dataHoraUpload',
            new_name='data_hora_upload',
        ),
        migrations.RenameField(
            model_name='anexo',
            old_name='nomeArquivo',
            new_name='nome_arquivo',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='dataFim',
            new_name='data_fim',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='dataInicio',
            new_name='data_inicio',
        ),
        migrations.RenameField(
            model_name='subtarefa',
            old_name='dataFim',
            new_name='data_fim',
        ),
        migrations.RenameField(
            model_name='subtarefa',
            old_name='dataInicio',
            new_name='data_inicio',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='dataFim',
            new_name='data_fim',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='dataInicio',
            new_name='data_inicio',
        ),
    ]
