# Generated by Django 6.0.6 on 2026-07-08 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_rename_caminhoarquivo_anexo_caminho_arquivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projeto',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio')), ('data_inicio__isnull', True), ('data_fim__isnull', True), _connector='OR'), name='projeto_data_fim_maior_ou_igual_inicio'),
        ),
        migrations.AddConstraint(
            model_name='subtarefa',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio')), ('data_inicio__isnull', True), ('data_fim__isnull', True), _connector='OR'), name='subtarefa_data_fim_maior_ou_igual_inicio'),
        ),
        migrations.AddConstraint(
            model_name='tarefa',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio')), ('data_inicio__isnull', True), ('data_fim__isnull', True), _connector='OR'), name='tarefa_data_fim_maior_ou_igual_inicio'),
        ),
    ]
