# Generated by Django 6.0.6 on 2026-07-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_codigorecuperacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cargoProfissional',
            new_name='cargo_profissional',
        ),
    ]
